--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -434,3 +434,5 @@ obj-$(CONFIG_CPU_FREQ_MSM) += cpufreq.o
 
 obj-$(CONFIG_WALL_CLK) += wallclk.o
 obj-$(CONFIG_WALL_CLK_SYSFS) += wallclk_sysfs.o
+
+obj-$(CONFIG_FORCE_FAST_CHARGE) += fastchg.o
